name: fintools
description: Fintools Project MFIN

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.2
  intl: ^0.17.0
  google_fonts: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/


flutter_intl:
  generate: true
  enabled: true
  class_name: I10n
  arb_dir: lib/utilities/i10n
  output_dir: lib/utilities/i10n